package com.reelbook.core.msg.enumeration;

public enum ModelMsgEnum
{
	INVALID_DESCRIPTION,
	INVALID_SUMMARY_DESCRIPTION,
	INVALID_PARENT,
	INVALID_HOUR,
	INVALID_PERIOD_OF_TIME,
	INVALID_ITEM_DUPLICATED,
	INVALID_RANGE_OF_NUMBERS;
}